= Social Media Reconaissance

Author: Dr. Jim Marquardson

Changelog

* 2022-08-15 Initial Version

Social engineering attacks are more effective when targeted toward specific individuals. Social media contains a treasure trove of information that social engineers can use to craft attacks.

== Learning Objectives

You should be able to:

* Define reconnaissance
* Restrict searches to social media sites

== Reconnaissance

Reconnaissance is the process of discovering information about a target that can be used to craft attacks in the future. Many ethical hackers say that the reconnaissance phase is the most important phase of a penetration test. Social engineers use reconnaissance to learn about their victims, including hobbies, projects they work on, colleagues, and more. Information that is publicly accessible on the internet is referred to as OSINT--open-source intelligence.

== Social Media Reconnaissance

. Pick a local business.
. Go to the business website and find some named employees. (If the business you visit does not name any employees, just pick a new business.)
. Craft a Google search to specifically search social media for their profiles. You can restrict searches to particular sites using `site:somesite.com`, where somesite.com is the site to search. For example:
.. "Sally Jones site:facebook.com"
.. "Sally Jones site:linkedin.com"
. LinkedIn is an especially good site for social engineers because many people in the business world have profiles.
. Record what you learn about the individual that could be used in a future attack.

== Reflection

* Why is social media such a rich source of reconnaissance information?
* Why might it be helpful to your career to list a lot of information on LinkedIn?

