[[glossary]]
= Glossary

[glossary]

access controls:: Rules that enforce the parts of a system that somebody can access. Supports data integrity and confidentiality.

availability:: Systems are working as intended at an acceptable level of service. Part of the information security triad.

confidentiality:: Restricting access to information to authorized people, often using access control lists and encryption. Part of the information security triad.

encryption:: Using a secret key and an algorithm to obscure data. Data can later be decrypted. Support confidentiality.

GPL v2:: Open source license that allows people to use, share, and modify source code. Proprietry software may use open source GPL v2 elements.

GPL v3:: Open source license that allows people to use, share, and mofify source code. Software that uses GPL v3 components must also be open source.

hashing:: A cryptographic process that produces a hash digest that represents the unique "fingerprint" of the data. Use to verify data integrity.

information security triad:: Confidentiality, integrity, and availability.

integrity:: Ensuring that information is accurate and complete. Changes to data are made by authorized individuals. Integrity is supported by access controls and often verified using cryptographic hashing. Part of the information security triad.

internet of things (IoT):: The trend of connecting many different kinds of devices to the internet. Examples include refrigerators, Amazon Echo, security cameras, light bulbs, and many other kinds of "smart" devices.

Kali Linux:: A Linux distribution that includes many cybersecurity tools installed by default.

key:: Encryption algorithms (ciphers) are pubicly available. Keys are used with algorithms to encrypt or decrypt data. Most encryption keys are kept secret, with the exception of public keys in asymmetric cryptography.

linux:: A class of open source operating systems that incorporate the Linux kernal and many open source applications.

linux: cd:: Linux command to change working directories.

linux: ls:: Linux command to list files and directories.

linux: man:: Linux command to launch the Linux manual.

linux: pwd:: Linux command to print the current working directory.

linux: whoami:: Linux command to show the current user in the terminal.

mainframe:: A powerful, centralized computer system that handles transactions and stores data. Relatively dumb client computers would send data to the mainframe where the data would be processed.

MIT license:: An open source license that lets people share, modify, and distribute source code as long as the code retains the MIT license.

open source software:: Software that can be distributed, modified, and used freely.

RedHat Linux:: An enterprise Linux Distribution often used in data centers. Developed by IBM.

redundancy:: Extra hardware (such as power supplies, servers, or network routers) that can continue operating in case of a failure. Supports system availability.

terminal:: The Linux application where commands can are typed.

Ubuntu Linux:: A Linux distribution for desktops, servers, and cloud devices. Developed by Canonical Ltd.

virtual machine:: A guest operating system running in a virtualization platform such as VirtualBox.

VirtualBox:: A popular open source virtualization platform for running virtual machines on a laptop or desktop computer.

virtualization:: Abstracting computer hardware so that virtual machines can be run on one physical computer.

virtualization guest:: A virtual machine that is running on a virtualization platform.

virtualizaiton host:: The base operating system that is supporting virtual machines.

Web 1.0:: The early days of the world wide web where strong technical skills were required to contribute content. Sometimes referred to as the "read-only" web.

Web 2.0:: The "read/write" web. Technological improvements made it easer for everybody to contribute content. Early contributions occurred through blogs, uploading video, and social media.


