= Encryption: How Https Works

Author: Dr. Jim Marquardson

Changelog

* 2022-08-15 Initial Version

== Learning Objectives

You should be able to:

* Explain how web browsers encrypt data

== RSA Key Exchange

Here is how your computer might communicate with https://www.google.com using TLS 1.2.

1. Your browser tells the server hosting https://www.google.com that you want a secure connection.
2. The web server hosting https://www.google.com sends you its public key.
3. You generate a random, temporary key. You encrypt the key with Google's public key. (Only Google can decrypt the key).
4. Google decrypts the temporary key with its private key.
5. Google encrypts the https://www.google.com web page data with the temporary key and a symmetric algorithm.
6. Your web browser decrypts the data with the temporary key and a symmetric algorithm.

Steps 1-4 are using asymmetric encryption. Steps 5-6 use symmetric encryption. Steps 5 and 6 will continue as long as you keep loading pages on https://www.google.com. When you close your web browser, or after a period of inactivity, your browser and Google will make 
the temporary key expires.

== Elliptic Curve Diffie-Helman Key Exchange

Here is how your computer might communicate with https://www.google.com using TLS 1.3.

1. Your browser generates an EC key pair, sends the public key to the server hosting https://www.google.com and asks for a secure connection.
2. The web server hosting https://www.google.com generates a new EC key pair and sends you its public key.
3. You generate a shared secret by multiplying your private key with Google's public key. You send some encrypted data using a symmetric cipher (like AES), using the shared secret key.
4. Google generates the same shared secret by multiplying its private key with your public key. Google can decrypt the data you sent.

With TLS 1.3, new keys are created for every new browsing session. If you close your web browser, all temporary keys are discarded. TLS 1.3 provides perfect forward secrecy.

== Reflection

* Who is responsible for ensuring the secure cryptographic protocols are used? Web browser developers? Legislators? Operating system vendors? Regular users of technology?
* Strong cryptography enables privacy. Some people use the internet for bad stuff. Should governments have a master key that can unlock all encrypted communications?

