= Cracking Passwords

Hashes are one-way functions so it is impossible to reconstruct the hash input from the hash output. But, for passwords, there are ways that password hashes can be "cracked." Several attacks will be demonstrated in this chapter.

== Learning Objectives

You should be able to:

* Use `john` to crack passwords using:
** Dictionary attacks
** Brute force attacks

== Crack Hashes

LinkedIn suffered a data breach in 2012. Millions of usernames and password hashes were leaked. Unfortunately, LinkedIn did not salt passwords, and it used the SHA1 algorithm. SHA1 was built for speed, which is great for password crackers. In this section, you will do just what the hackers did--try to crack the LinkedIn passwords. For simplicity, only a small subset of the actual passwords are included here.

. Launch the Kali virtual machine.
. Open a terminal.
. Run the following command. Note that it will delete any files you added or changed in the *cyfunfiles* folder.
+
[source,shell]
----
cd ~
rm -rf cyfunfiles
----
. Run the following command to download files from the internet. This will create a new folder called *cyfunfiles* in your home directory.
+
[source,shell]
----
git clone https://github.com/jimmarq/cyfunfiles
----
. Change directories to the *cyfunfiles* directory.
+
[source,shell]
----
cd cyfunfiles
----
. Change directories to the *crypto_crack_hashes* subdirectory.
+
[source,shell]
----
cd crypto_crack_hashes
----
. Look at the files in the folder with `ls`.
+
[source,shell]
----
ls
----

In the next sections, you will perform various attacks using a program called John (the Ripper, but many people just refer to the program as "John.") A more sophisticated program for cracking hashes is Hashcat, but it does not run well on virtual machines.

=== Dictionary Attack

Dictionary attacks hash all of the words in a list and compare those hashes to the passwords being cracked. Dictionary attacks often work well because people are predictable and do not choose random passwords.

. Run the following command to run a dictionary attack.
+
[source,shell]
----
john --wordlist=/usr/share/wordlists/metasploit/password.lst --format=Raw-SHA1 linkedin_hashes.txt
----
+
The file /usr/share/wordlists/metasploit/password.lst has about 90,000 passwords.
. The attack should run very fast. All 90,000 passwords were checked against the LinkedIn hashes very quickly.
. If you missed the hashes in the terminal, you can check to see what has been cracked with:
+
[source,shell]
----
john -show linkedin_hashes.txt
----

When dictionary attacks fail, you can:

. find a bigger dictionary, or
. try a different type of attack.

In the next section, you'll try a brute force attack.

=== Brute Force Attack

In a brute force attack, all possible passwords for given character sets will be tried. The larger the character set, the longer the attack can take to finish. Some of John's different preconfigured modes are:

* Lower: lowercase
* Upper: uppercase
* LowerNum: lowercase and numbers
* UpperNum: upper case and numbers
* ASCII: lower case, upper case, numbers, and symbols
* Alnum: lower case, upper case, and numbers

. Try cracking passwords with all lowercase letters.
+
[source,shell]
----
john -incremental=Lower linkedin_hashes.txt
----
. Press space bar while the attack is running to see cracking metrics. John reports several metrics:
.. g/s: Successful guesses per second
.. p/s, c/s, and C/s describe subtle variations of how many passwords can be tried per second. The following shows that John can crack 12,000K (12 million) SHA1 hashes per second.
+
```
6g 0:00:00:05  3/3 1.197g/s 12003Kp/s 12003Kc/s 12003KC/s hoogb..hoo2s
```

=== Clean up / Restart

If you want to delete the hashes to try different attacks you will have to delete the "potfile" (where hashes are stored).

[source,shell]
----
rm ~/.john/john.pot
----

== Evaluating Bcrypt

The bcrypt algorithm has 2 defenses against password cracking: 1) it intentionally wastes CPU to make it slow, and 2) it salts by default.

. Run the following command to try cracking the bcrypt hashes for `cat` (because "wildcat" would take entirely too long to crack) and `1999` (in honor of his purpleness). These passwords would be trivial to crack if they were hashed using MD5 without salt.
+
[source,shell]
----
john bcrypt_hashes.txt
----
. While the attack is in progress, press the space bar to evaluate the cracking speed.
+
```
1g 0:00:02:53 14.10% 2/3 (ETA: 05:05:41) 0.005774g/s 121.8p/s 138.6c/s 138.6C/s stacerom..1donald
```

On the same hardware, John can crack:

* 12 million SHA1 hashes per second
* 125 bcrypt hashes per second

In this case, cracking bcrypt hashes is approximately 100,000 times slower. So if it took a week to crack a SHA1 hash, it would take 1,923 years to crack that same password if it were hashed using bcrypt. There are some caveats about hardware and software efficiency, but the fact remains that bcrypt hashes are much harder to crack.

== Challenge

* Use `john` to crack passwords in the Linux `shadow` file with:
+
[source,shell]
----
cd ~
sudo cp /etc/shadow shadow
john shadow
----
* Create several user accounts, set their passwords, and try to crack those passwords.
* Use the following command to show any cracked passwords.
+
[source,shell]
----
john shadow --show
----

== Reflection

* Why don't people choose stronger passwords?
* If you picked a strong password, would brute force and dictionary attacks have been successful?

