= Importing

Python has a lot of features. So far, chapters have focused on core functionality. It is possible to "import" python libraries that do more advanced work.

== Learning Objectives

You should be able to:

* Describe what importing does
* Import libraries
* Use imported library functions

== Importing

Python is broken down into modules. A python file is a single module. Modules are organized in packages. Packages are folders of different modules. So there could be an entire package (i.e., folder) of python modules (i.e., .py files) that could help you manipulate images, download web pages, decrypt data, and more.

Python comes with many packages that can be imported without having to install anything. In the next section, you will work with the *datetime*, *os*, and *hashlib* packages.

== Datetime Library

Dates are hard. Really hard. Your average elementary school student knows how calendars and clocks work, but behind the basics lies a huge amount of complexity. Developers often get bitten by bugs due to leap years, leap seconds, time zones, and other date-related issues. Python's *datetime* library helps developers work with dates.

. From the Kali terminal, launch a python interactive shell.
+
[source,sh]
----
python
----
. You will now see prompts like:
+
----
>>>
----
+
The code you write at these prompts must be python code.
. Run the following code to try to get the current date. (It will fail.)
+
[source,python]
----
datetime.date.today()
----
+
You should see an error: "NameError: name 'datetime' is not defined." The *datetime* library definitely exists, but we have not imported it, yet.
. The entire *datetime* package can be imported with the following code.
+
[source,python]
----
import datetime
----
+
It looks like nothing happens when you run the above code. But what python does is load all of the *datetime* python files into your current program (the shell).
. You can now access the *datetime* features.
+
[source,python]
----
datetime.date.today()
----
+
The code will now produce:
+
----
datetime.date(2022, 6, 20)
----
+
(Of course, the date produced will depend on the date when you run the code.)
. Technically, you imported way more functionality than you needed to. If the only *datetime* feature we need is the *date* functionality, it can be imported specifically.
+
[source,python]
----
from datetime import date
date.today()
----
+
The above code goes into the *datetime* package and only loads the *date* module. Generally, only importing what you need and nothing else is preferred.

== Os Library

The *os* library has information about operating system features.

. Run the following code.
+
[source,python]
----
import os
os.getlogin()
----
+
This will print the name of the logged-in user--'kali.'
. Check to see if two folders exist.
+
[source,python]
----
os.path.exists("/home/kali/Docs")
os.path.exists("/home/kali/Documents")
----
. Check your current working directory.
+
[source,python]
----
os.getcwd()
----

Find other features here: https://docs.python.org/3/library/os.html.

== Hashlib Library

Python can be used to calculate hashes.

. Run the following code.
+
[source,python]
----
import hashlib
hashlib.sha256(b"watermelon").hexdigest()
----
+
The result should be:
+
----
'31a2d5282683edb3a22c565f199aa96fb9ffb3107af35aad92ee1cd567cfc25d'
----
. Notice the "b" in front of "watermelon". The "b" tells python to treat the string "watermelon" as bytes (0s and 1s) using ASCII encoding.
. To calculate the hash of a string variable, the *bytes()* function must be used.
+
[source,python]
----
password = "watermelon"
hashlib.sha256(bytes(password, 'ascii')).hexdigest()
----
+
The hashlib.sha256() function requires bytes (not a string), so the *bytes()* function converts the string to bytes according to the character encoding specified.
. To see what else is in the *hashlib* library, run the following code:
+
----
dir(hashlib)
----
. If you see something interesting, you can dig deeper into the official documentation at https://docs.python.org/3/library/hashlib.html.
. For example, for password storage, *scrypt* would be better than *sha256*. Honestly, the python documentation does not give a great explanation for using *scrypt*. But, the following code would work.
+
----
hashlib.scrypt(b"watermelon", salt=os.urandom(16), n=4, r=8, p=1)
----
+
Run the above code several times. Notice that a different hash is created each time. That is because you are pulling in random entropy from the *os* library each time.

== Challenge: Hash Items in a List

The following code will hash a single password stored in the *password* variable:

[source,python]
----
import hashlib
password = "watermelon"
sha = hashlib.sha256(bytes(password, 'ascii'))
output = sha.hexdigest()
print(f"{password}:{output}")
----

. Create a file called *hashem.py*.
. Inside *hashem.py*, copy and then modify the above code:
.. Change the name of the *password* variables to *passwords*.
.. Set the value of the *passwords* variable to list of passwords (pick any random words).
.. Loop through each *password* in *passwords*.
.. In each loop, calculate the sha256 hash of the password.
.. Print the password and the hash, separated by a colon.

== Reflection

* What kinds of libraries would be most useful to help you solve problems?
* Why is it a good idea to import the minimum number of libraries needed to solve a problem?

